crs:
  base-url: https://your-crs-domain.com
  vendor-id: CLARITY
  channel-id: WEB
  location-id: 920
  terminal-id: 1234

payment:
  api:
    hostname: https://webapps3int.chicago.gov
    transaction-endpoint: /hostedpayments/hostedPaymentPages/transaction