crs:
  base-url: https://your-crs-domain.com
  vendor-id: CLARITY
  channel-id: WEB
  location-id: 920
  terminal-id: 1234

payment:
  api:
    hostname: https://webapps3int.chicago.gov
    transaction-endpoint: /hostedpayments/hostedPaymentPages/transaction
    username: your-username
    password: your-password

cpg:
  returnUrl: https://webapps3int.chicago.gov/hostedpayments/#/redirect-url?action=returnUrl
  cancelUrl: https://webapps3int.chicago.gov/hostedpayments/#/redirect-url?action=cancelUrl
  paymentTokenPurpose: ADHOC
  locationId: 920
  channel: WEB
  terminalId: 1234
  vendorId: CLARITY
  applicationName: CHIPAY_WALLET
  encryptionKey: TBD

file:
  upload:
    max-size: 10485760          # 10 MB
    allowed-extensions: jpg,png,pdf,docx
clamav:
  host: localhost
  port: 3310

aws:
  s3:
    bucket: my-app-uploads
    region: us-east-1
    upload-prefix: uploads/
    presigned-url-ttl-seconds: 3600
    server-side-encryption: AES256